"""initial_schema

Revision ID: dc0df178a1e1
Revises: 
Create Date: 2026-09-18 23:26:40.827447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc0df178a1e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'last_updated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_supplier_id'), table_name='products')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.drop_index(op.f('idx_po_items_po_id'), table_name='purchase_order_items')
    op.drop_index(op.f('idx_po_items_product_id'), table_name='purchase_order_items')
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=mysql.ENUM('PENDING', 'ORDERED', 'RECEIVED', 'CANCELLED'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.drop_index(op.f('idx_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.drop_index(op.f('idx_sales_product_id'), table_name='sales')
    op.drop_index(op.f('idx_sales_sale_date'), table_name='sales')
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.alter_column('suppliers', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'MANAGER', 'EMPLOYEE'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('ADMIN', 'MANAGER', 'EMPLOYEE'),
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'"))
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.alter_column('suppliers', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.create_index(op.f('idx_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('idx_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.create_index(op.f('idx_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'ORDERED', 'RECEIVED', 'CANCELLED'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.create_index(op.f('idx_po_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_po_items_po_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index(op.f('idx_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.alter_column('inventory', 'last_updated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
